-- Impact Stories table for HerRise admin (public read, authenticated write)
-- Run this in Supabase Dashboard → SQL Editor if the table doesn't exist.

create table if not exists public.impact_stories (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text not null,
  image text not null,
  date text not null,
  read_time text not null,
  location text not null,
  category text not null,
  author text not null,
  author_role text not null,
  content text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.impact_stories enable row level security;

create policy "impact_stories_select"
  on public.impact_stories for select
  to anon, authenticated
  using (true);

create policy "impact_stories_insert"
  on public.impact_stories for insert
  to authenticated
  with check (true);

create policy "impact_stories_update"
  on public.impact_stories for update
  to authenticated
  using (true)
  with check (true);

create policy "impact_stories_delete"
  on public.impact_stories for delete
  to authenticated
  using (true);

create or replace function public.set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists impact_stories_updated_at on public.impact_stories;
create trigger impact_stories_updated_at
  before update on public.impact_stories
  for each row execute function public.set_updated_at();
