-- She Stories table: title, name, content, change_achieved (jsonb), quote, image_url, image_caption
create table if not exists public.she_stories (
  id bigint generated by default as identity primary key,
  title text not null,
  name text not null,
  content text not null default '',
  change_achieved jsonb not null default '[]'::jsonb,
  quote text not null default '',
  image_url text not null default '',
  image_caption text not null default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.she_stories enable row level security;

create policy "she_stories_select"
  on public.she_stories for select
  to anon, authenticated
  using (true);

create policy "she_stories_insert"
  on public.she_stories for insert
  to authenticated
  with check (true);

create policy "she_stories_update"
  on public.she_stories for update
  to authenticated
  using (true)
  with check (true);

create policy "she_stories_delete"
  on public.she_stories for delete
  to authenticated
  using (true);

drop trigger if exists she_stories_updated_at on public.she_stories;
create trigger she_stories_updated_at
  before update on public.she_stories
  for each row execute function public.set_updated_at();

comment on table public.she_stories is 'She Stories: short stories with change_achieved and quote. Images in storage bucket she-stories.';
